### **Chapter: Understanding NumPy Arrays**
### **Lesson #1: Introducing arrays**

---

**NumPy** is the core library for scientific computing in Python. Different libraries such as *Sci-Py*, *Matplotlib*, and *Pandas* are built in top of **NumPy API**. Even popular machine learning libraries such as *Scikit-learn* and *Tensorflow* uses **NumPy arrays** as inputs. Any person or developers who uses numbers for different types of computations will come across NumPy Arrays.

**Array** is the main object of NumPy and stores data in a grid-like structure that is similar in spreadsheets or tables. Arrays can have any number of dimensions and each dimensions can have any length.

Creating one-dimensional array in NumPy.

In [2]:
import numpy as np

city = ["Charlotte", "New York", "Orlando", "Boston", "Washington", "Cleveland"]
one_d_ar = np.array(city)
print(one_d_ar)

['Charlotte' 'New York' 'Orlando' 'Boston' 'Washington' 'Cleveland']


Creating two-dimensional array.

In [3]:
city_and_team = [
    ["Boston", "Celtics"],
    ["Brooklyn", "Nets"],
    ["New York", "Knicks"],
    ["Philadelphia", "76ers"],
    ["Toronto", "Raptors"]
]
two_d_arr = np.array(city_and_team)
print(two_d_arr)

[['Boston' 'Celtics']
 ['Brooklyn' 'Nets']
 ['New York' 'Knicks']
 ['Philadelphia' '76ers']
 ['Toronto' 'Raptors']]


Creating three-dimensional array.

In [4]:
city_team_conf = [
    [
        ["Boston", "Celtics", "East"],
        ["Brooklyn", "Nets", "East"],
        ["New York", "Knicks", "East"],
        ["Philadelphia", "76ers", "East"],
        ["Toronto", "Raptors", "East"]
    ],
    [
        ["Utah", "Jazz", "West"],
        ["Golden State", "Warriors", "West"],
        ["Los Angeles", "Clippers", "West"],
        ["Los Angeles", "Lakers", "West"],
        ["Phoenix", "Suns", "West"]
    ]
]
three_d_arr = np.array(city_team_conf)
print(three_d_arr)

[[['Boston' 'Celtics' 'East']
  ['Brooklyn' 'Nets' 'East']
  ['New York' 'Knicks' 'East']
  ['Philadelphia' '76ers' 'East']
  ['Toronto' 'Raptors' 'East']]

 [['Utah' 'Jazz' 'West']
  ['Golden State' 'Warriors' 'West']
  ['Los Angeles' 'Clippers' 'West']
  ['Los Angeles' 'Lakers' 'West']
  ['Phoenix' 'Suns' 'West']]]


The difference of Python list and NumPy array is how they stored values. Python list stores values or datas with different datatype (**heterogenous**) in the same dimension while NumPy array stores values or datas with the same datatype (**homogenous**).

In [6]:
# Python list
nba_player = ["Nikola Jokić", "Denver Nuggets", "Center", 211, 128]
print(nba_player)

# NumPy Array
nba_player = np.array(["Nikola Jokić", "Denver Nuggets", "Center", 211, 128])
print(nba_player)

['Nikola Jokić', 'Denver Nuggets', 'Center', 211, 128]
['Nikola Jokić' 'Denver Nuggets' 'Center' '211' '128']


In NumPy, we can create arrays from passing a data stored in list or create from scratch using different methods such as `np.zeros()`, `np.random.random()`, and `np.arrange()`.

Creating arrays from scratch using `np.zeros()`

In [ ]:
# Create array with 1 row and 5 columns of zero elements
print(np.zeros(5))
print()

# Crate array with 9 rows and 4 columns of zero elements
zero_arr = np.zeros((9, 4))
print(zero_arr)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Creating arrays from scratch using `np.randon.random()`

In [108]:
# Generate random single value if shape are not specified
print(np.random.random())
print()

# Generate array with 1 row and 5 columns with random numbers
print(np.random.random((5)))
print()

# Generate array with 9 rows and 4 columns with random numbers
random_arr = np.random.random((9, 4))
print(random_arr)
print()

0.8337048266116494

[0.10086681 0.30971223 0.18080776 0.13651852 0.72306562]

[[0.44479813 0.73075998 0.92908972 0.71965143]
 [0.19757678 0.84448921 0.92609534 0.91420652]
 [0.19748932 0.93776852 0.93473916 0.0928538 ]
 [0.09324294 0.05453681 0.64964861 0.1364935 ]
 [0.75061445 0.36512472 0.46643946 0.39858305]
 [0.05318076 0.08057443 0.35873819 0.30087336]
 [0.82718629 0.09170883 0.14272064 0.17755719]
 [0.25616426 0.7655109  0.99292507 0.7974224 ]
 [0.42876414 0.53555785 0.8973674  0.54636436]]

