### **Chapter: Understanding NumPy Arrays**
### **Lesson #1: Introducing arrays**

---

**NumPy** is the core library for scientific computing in Python. Different libraries such as *Sci-Py*, *Matplotlib*, and *Pandas* are built in top of **NumPy API**. Even popular machine learning libraries such as *Scikit-learn* and *Tensorflow* uses **NumPy arrays** as inputs. Any person or developers who uses numbers for different types of computations will come across NumPy Arrays.

**Array** is the main object of NumPy and stores data in a grid-like structure that is similar in spreadsheets or tables. Arrays can have any number of dimensions and each dimensions can have any length.

Creating one-dimensional array in NumPy.

In [2]:
import numpy as np

city = ["Charlotte", "New York", "Orlando", "Boston", "Washington", "Cleveland"]
one_d_ar = np.array(city)
print(one_d_ar)

['Charlotte' 'New York' 'Orlando' 'Boston' 'Washington' 'Cleveland']


Creating two-dimensional array.

In [3]:
city_and_team = [
    ["Boston", "Celtics"],
    ["Brooklyn", "Nets"],
    ["New York", "Knicks"],
    ["Philadelphia", "76ers"],
    ["Toronto", "Raptors"]
]
two_d_arr = np.array(city_and_team)
print(two_d_arr)

[['Boston' 'Celtics']
 ['Brooklyn' 'Nets']
 ['New York' 'Knicks']
 ['Philadelphia' '76ers']
 ['Toronto' 'Raptors']]


Creating three-dimensional array.

In [4]:
city_team_conf = [
    [
        ["Boston", "Celtics", "East"],
        ["Brooklyn", "Nets", "East"],
        ["New York", "Knicks", "East"],
        ["Philadelphia", "76ers", "East"],
        ["Toronto", "Raptors", "East"]
    ],
    [
        ["Utah", "Jazz", "West"],
        ["Golden State", "Warriors", "West"],
        ["Los Angeles", "Clippers", "West"],
        ["Los Angeles", "Lakers", "West"],
        ["Phoenix", "Suns", "West"]
    ]
]
three_d_arr = np.array(city_team_conf)
print(three_d_arr)

[[['Boston' 'Celtics' 'East']
  ['Brooklyn' 'Nets' 'East']
  ['New York' 'Knicks' 'East']
  ['Philadelphia' '76ers' 'East']
  ['Toronto' 'Raptors' 'East']]

 [['Utah' 'Jazz' 'West']
  ['Golden State' 'Warriors' 'West']
  ['Los Angeles' 'Clippers' 'West']
  ['Los Angeles' 'Lakers' 'West']
  ['Phoenix' 'Suns' 'West']]]


The difference of Python list and NumPy array is how they stored values. Python list stores values or datas with different datatype (**heterogenous**) in the same dimension while NumPy array stores values or datas with the same datatype (**homogenous**).

In [6]:
# Python list
nba_player = ["Nikola Jokić", "Denver Nuggets", "Center", 211, 128]
print(nba_player)

# NumPy Array
nba_player = np.array(["Nikola Jokić", "Denver Nuggets", "Center", 211, 128])
print(nba_player)

['Nikola Jokić', 'Denver Nuggets', 'Center', 211, 128]
['Nikola Jokić' 'Denver Nuggets' 'Center' '211' '128']


In NumPy, we can create arrays from passing a data stored in list or create from scratch using different methods such as `np.zeros()`, `np.random.random()`, and `np.arrange()`.

Creating arrays from scratch using `np.zeros()`

In [26]:
zero_arr = np.zeros(shape=(9, 4)) # shape=(rows, columns)
print(zero_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Creating arrays from scratch using `np.randon.random()`

In [48]:
random_arr = np.random.random((9, 4))
print(random_arr)

[[0.72947482 0.10920206 0.39074733 0.64776788]
 [0.62005087 0.81801879 0.66636457 0.43861761]
 [0.15843784 0.1345215  0.85196063 0.64323213]
 [0.58639535 0.90659104 0.60587593 0.32940142]
 [0.32390387 0.08839781 0.40989644 0.01607453]
 [0.61713309 0.63046778 0.69636027 0.33780927]
 [0.28808048 0.53922397 0.14174031 0.22799715]
 [0.73571518 0.41592087 0.08427995 0.88507087]
 [0.12926264 0.87419132 0.2693703  0.10805212]]
