In [94]:
import pandas as pd 
import numpy as np

df = pd.read_csv("../Datasets/mental_health.csv")

Creating one-dimensional array.

In [107]:
person_id = np.array(df["Person_ID"])
age = np.array(df["Age"])

Creating two-dimensional array.

In [113]:
# Row-wise
row_wise_arr = np.array([person_id, age])
print(row_wise_arr)
print()

# Column-wise
column_wise_arr = np.column_stack([person_id, age])
print(column_wise_arr)

[[   1    2    3 ... 1998 1999 2000]
 [  54   44   30 ...   28   56   38]]

[[   1   54]
 [   2   44]
 [   3   30]
 ...
 [1998   28]
 [1999   56]
 [2000   38]]


In [119]:
three_d_arr = np.array([
    [person_id[:1000],age[:1000]], # First matrix
    [person_id[1000:],age[1000:]] # Second matrix
])
print(three_d_arr)

[[[   1    2    3 ...  998  999 1000]
  [  54   44   30 ...   29   55   55]]

 [[1001 1002 1003 ... 1998 1999 2000]
  [  54   21   21 ...   28   56   38]]]
