### **Lesson: Introducing Arrays**

Building **NumPy Arrays** in different methods such as building **NumPy Array** using **Pandas** library or building from scratch using different methods such as `np.zeros()`, `np.random.random()`, and `np.arange()`.

#### **Setup environment**

Setup the libraries and modules to use to create *NumPy Arrays* by running the code snippet below.

In [188]:
import pandas as pd
import numpy as np
from numpy import ndarray

df = pd.read_csv("../Datasets/mental_health.csv")

#### **Create 1D Array**

Create 1D Array using Pandas Library by extracting or selecting an example of a Series from the given DataFrame.

In [189]:
one_dim_array = np.array(df["Person_ID"])
print("1D Array:")
print(one_dim_array)

1D Array:
[   1    2    3 ... 1998 1999 2000]


### **Create 2D Array**

Create 2D Array using `np.column_stack()` method.

In [190]:
two_dim_array = np.column_stack([df["Person_ID"], df["Age"]])
print("2D Array:")
print(two_dim_array)

2D Array:
[[   1   54]
 [   2   44]
 [   3   30]
 ...
 [1998   28]
 [1999   56]
 [2000   38]]


### **Create 3D Array**

Create 3D Array by combining the methods: `np.array()` and `np.column_stack()`

In [191]:
person_id1 = df["Person_ID"][:1000]
occupation1 = df["Occupation"][:1000]

person_id2 = df["Person_ID"][1000:]
occupation2 = df["Occupation"][1000:]

three_dim_array = np.array([
    np.column_stack([person_id1, occupation1]),
    np.column_stack([person_id2, occupation2])
])

print("3D Array:")
print(three_dim_array)

3D Array:
[[[1 'Student']
  [2 'Student']
  [3 'Employed']
  ...
  [998 'Employed']
  [999 'Unemployed']
  [1000 'Student']]

 [[1001 'Unemployed']
  [1002 'Student']
  [1003 'Student']
  ...
  [1998 'Employed']
  [1999 'Student']
  [2000 'Unemployed']]]


### **Create 1D Array using `np.zeroes()`**

Create 1D Array with `0` elements by using `np.zeroes()`.

In [192]:
def create_zero_elem_arr(data_shape: tuple) -> ndarray:
    """Create NumPy Array based on the given dataset shape."""
    zero_elem_arr = np.zeros(shape=data_shape)
    return zero_elem_arr

one_dim_zero_elem_array = create_zero_elem_arr(data_shape=(100))
print("1D Array using np.zeros(100):")
print(one_dim_zero_elem_array)

1D Array using np.zeros(100):
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


### **Create 2D Array using `np.zeroes()`**

Create 2D Array with `0` elements by using `np.zeroes()`.

In [193]:
two_dim_zero_elem_array = create_zero_elem_arr(data_shape=(100, 4))
print("2D Array using np.zeroes(100, 4):")
print(two_dim_zero_elem_array)

2D Array using np.zeroes(100, 4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0

### **Create 3D Array using `np.zeroes()`**

Create 3D Array with `0` elements by using `np.zeroes()`.

In [194]:
three_dim_zero_elem_array = create_zero_elem_arr(data_shape=(3, 10, 5))
print("3D Array using np.zeroes(3, 10, 5):")
print(three_dim_zero_elem_array)

3D Array using np.zeroes(3, 10, 5):
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


### **Create 1D Array using np.random.random()**

Create 1D Array with random elements using `np.random.random()`.

In [195]:
def create_random_elem_arr(data_shape: tuple) -> ndarray:
    """Create NumPy Array with random elements based on the given dataset shape"""
    random_elem_arr = np.random.random(size=data_shape)
    return random_elem_arr

one_dim_random_elem_array = create_random_elem_arr(data_shape=(50))
print("1D Array using np.random.random(50):")
print(one_dim_random_elem_array)

1D Array using np.random.random(50):
[0.46312717 0.35913114 0.3742013  0.23698219 0.46749181 0.50940321
 0.40860538 0.51064386 0.75513053 0.55455281 0.61480547 0.73867299
 0.62568614 0.78811628 0.85456856 0.09067468 0.78003797 0.11434038
 0.38677144 0.27601113 0.3165683  0.59637053 0.47415644 0.27171667
 0.58245558 0.5455908  0.71929243 0.98411846 0.98967845 0.48396912
 0.87327381 0.3523038  0.26845776 0.89683932 0.74209964 0.70904282
 0.18345341 0.43221068 0.99885637 0.97003491 0.58284944 0.55149729
 0.05590239 0.36974046 0.95657636 0.537653   0.40064936 0.68350996
 0.9618178  0.62237162]


### **Create 2D Array using np.random.random()**

Create 2D Array with random elements using `np.random.random()`.

In [196]:
two_dim_random_elem_array = create_random_elem_arr(data_shape=(12, 4))
print("2D Array using np.random.random(12, 4):")
print(two_dim_random_elem_array)

2D Array using np.random.random(12, 4):
[[0.71890121 0.89152252 0.53326005 0.67822167]
 [0.17247912 0.72435418 0.78429163 0.40238062]
 [0.65384986 0.77165404 0.71174913 0.38414745]
 [0.99105657 0.23438565 0.72261656 0.61877583]
 [0.20448596 0.47088262 0.22714709 0.21615669]
 [0.50971597 0.84630917 0.01953369 0.27773432]
 [0.44042855 0.39085722 0.36801041 0.91237767]
 [0.82580706 0.0787943  0.67516794 0.09823361]
 [0.75664357 0.69066041 0.2041927  0.57867777]
 [0.73952225 0.39184252 0.83979364 0.22958794]
 [0.46817669 0.8371747  0.34758224 0.92351072]
 [0.47773847 0.54449985 0.09697861 0.18748185]]


### **Create 3D Array using np.random.random()**

Create 3D Array with random elements using `np.random.random()`.

In [197]:
three_dim_random_elem_array = create_random_elem_arr(data_shape=(2, 50, 3))
print("3D Array using np.random.random(2, 50, 3):")
print(three_dim_random_elem_array)

3D Array using np.random.random(2, 50, 3):
[[[0.63863247 0.01661762 0.33262174]
  [0.56040552 0.77772039 0.22557336]
  [0.17438199 0.44677301 0.97093162]
  [0.02948611 0.29761884 0.75961765]
  [0.042136   0.06896177 0.70807222]
  [0.44205665 0.50486442 0.51442717]
  [0.42812611 0.52273019 0.7830944 ]
  [0.18022849 0.55606997 0.27461614]
  [0.09721791 0.46229286 0.19355084]
  [0.75456175 0.38584302 0.63158999]
  [0.42709025 0.72594715 0.65627149]
  [0.54947386 0.02774209 0.68877191]
  [0.83998337 0.37557357 0.73386058]
  [0.24603914 0.98255517 0.36059099]
  [0.69099852 0.32951278 0.16603815]
  [0.34705435 0.507038   0.97552522]
  [0.54882729 0.3471223  0.41393496]
  [0.46674442 0.17622651 0.58728936]
  [0.01563575 0.92351584 0.82074689]
  [0.01340727 0.77817903 0.6469077 ]
  [0.00459418 0.43429403 0.54561679]
  [0.80534724 0.91957043 0.8438073 ]
  [0.41866911 0.2142852  0.78889981]
  [0.61271566 0.70042062 0.0829025 ]
  [0.7814258  0.89383436 0.71490292]
  [0.71047788 0.93930244 0.07708

### **Create 1D Array using np.arange()**

Create 1D Array with a range of values for the elements using `np.arange()`.

In [198]:
def create_range_elem_arr(data_shape: tuple) -> ndarray:
    if type(data_shape) is int:
        range_elem_arr = np.arange(data_shape)

    elif len(data_shape) == 2:
        range_elem_arr = np.arange(data_shape[0], data_shape[1])

    elif len(data_shape) == 3:
        range_elem_arr = np.arange(data_shape[0], data_shape[1], data_shape[2])

    else:
        raise Exception("Invalid parameters!")

    return range_elem_arr

one_dim_range_elem_array = create_range_elem_arr(data_shape=(51))
print("1D Array using np.arange(51):")
print(one_dim_range_elem_array)

1D Array using np.arange(51):
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


### **Create 2D Array using np.arange()**

Create 2D Array with a range of values for the elements using `np.arange()` and `np.column_stack()`.

In [199]:
two_dim_range_elem_array = np.column_stack([np.arange(1, 101), np.arange(101, 201)])
print("2D Array using np.arange(1, 101) and np.arange(101, 201):")
print(two_dim_range_elem_array)

2D Array using np.arange(1, 101) and np.arange(101, 201):
[[  1 101]
 [  2 102]
 [  3 103]
 [  4 104]
 [  5 105]
 [  6 106]
 [  7 107]
 [  8 108]
 [  9 109]
 [ 10 110]
 [ 11 111]
 [ 12 112]
 [ 13 113]
 [ 14 114]
 [ 15 115]
 [ 16 116]
 [ 17 117]
 [ 18 118]
 [ 19 119]
 [ 20 120]
 [ 21 121]
 [ 22 122]
 [ 23 123]
 [ 24 124]
 [ 25 125]
 [ 26 126]
 [ 27 127]
 [ 28 128]
 [ 29 129]
 [ 30 130]
 [ 31 131]
 [ 32 132]
 [ 33 133]
 [ 34 134]
 [ 35 135]
 [ 36 136]
 [ 37 137]
 [ 38 138]
 [ 39 139]
 [ 40 140]
 [ 41 141]
 [ 42 142]
 [ 43 143]
 [ 44 144]
 [ 45 145]
 [ 46 146]
 [ 47 147]
 [ 48 148]
 [ 49 149]
 [ 50 150]
 [ 51 151]
 [ 52 152]
 [ 53 153]
 [ 54 154]
 [ 55 155]
 [ 56 156]
 [ 57 157]
 [ 58 158]
 [ 59 159]
 [ 60 160]
 [ 61 161]
 [ 62 162]
 [ 63 163]
 [ 64 164]
 [ 65 165]
 [ 66 166]
 [ 67 167]
 [ 68 168]
 [ 69 169]
 [ 70 170]
 [ 71 171]
 [ 72 172]
 [ 73 173]
 [ 74 174]
 [ 75 175]
 [ 76 176]
 [ 77 177]
 [ 78 178]
 [ 79 179]
 [ 80 180]
 [ 81 181]
 [ 82 182]
 [ 83 183]
 [ 84 184]
 [ 85 185]
 [ 86 1

### **Create 3D Array using np.arange()**

Create 3D Array with a range of values for the elements using `np.arange()` and `np.column_stack()`.

In [200]:
three_dim_range_elem_array = np.array([
    np.column_stack([np.arange(1, 101), np.arange(101, 201)]),
    np.column_stack([np.arange(1, 101), np.arange(101, 201)]),
])
print("3D Array using np.arange(1, 101) and np.arange(101, 201):")
print(three_dim_range_elem_array)

3D Array using np.arange(1, 101) and np.arange(101, 201):
[[[  1 101]
  [  2 102]
  [  3 103]
  [  4 104]
  [  5 105]
  [  6 106]
  [  7 107]
  [  8 108]
  [  9 109]
  [ 10 110]
  [ 11 111]
  [ 12 112]
  [ 13 113]
  [ 14 114]
  [ 15 115]
  [ 16 116]
  [ 17 117]
  [ 18 118]
  [ 19 119]
  [ 20 120]
  [ 21 121]
  [ 22 122]
  [ 23 123]
  [ 24 124]
  [ 25 125]
  [ 26 126]
  [ 27 127]
  [ 28 128]
  [ 29 129]
  [ 30 130]
  [ 31 131]
  [ 32 132]
  [ 33 133]
  [ 34 134]
  [ 35 135]
  [ 36 136]
  [ 37 137]
  [ 38 138]
  [ 39 139]
  [ 40 140]
  [ 41 141]
  [ 42 142]
  [ 43 143]
  [ 44 144]
  [ 45 145]
  [ 46 146]
  [ 47 147]
  [ 48 148]
  [ 49 149]
  [ 50 150]
  [ 51 151]
  [ 52 152]
  [ 53 153]
  [ 54 154]
  [ 55 155]
  [ 56 156]
  [ 57 157]
  [ 58 158]
  [ 59 159]
  [ 60 160]
  [ 61 161]
  [ 62 162]
  [ 63 163]
  [ 64 164]
  [ 65 165]
  [ 66 166]
  [ 67 167]
  [ 68 168]
  [ 69 169]
  [ 70 170]
  [ 71 171]
  [ 72 172]
  [ 73 173]
  [ 74 174]
  [ 75 175]
  [ 76 176]
  [ 77 177]
  [ 78 178]
  [ 79