In [94]:
import pandas as pd 
import numpy as np

df = pd.read_csv("../Datasets/mental_health.csv")

Creating one-dimensional array.

In [98]:
person_id = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
age = np.array([54, 44, 30, 58, 23, 36, 54, 34, 38, 37])

Creating two-dimensional array.

In [101]:
# Row-wise
print(np.array([person_id, age]))

# Column-wise
print(np.column_stack([person_id, age]))

[[ 1  2  3  4  5  6  7  8  9 10]
 [54 44 30 58 23 36 54 34 38 37]]
[[ 1 54]
 [ 2 44]
 [ 3 30]
 [ 4 58]
 [ 5 23]
 [ 6 36]
 [ 7 54]
 [ 8 34]
 [ 9 38]
 [10 37]]
